binary:
	@echo please wait...
	@if exist bin\ (echo dir ok) else (mkdir bin\)
	@echo running compiler...
	@csc -recurse:src/*.cs -out:bin/bluebird.exe -nologo
clean:
	@echo deleting binary...
	@del bin\bluebird.exe
run:
	@echo executing...
	@bin\bluebird.exe
