binary:
	@echo running compiler...
	@csc main.cs pingStuff.cs helpCommand.cs emergency.cs -out:bin\bluebird.exe -nologo
clean:
	@echo deleting binary...
	@del bin\bluebird.exe
run:
	@echo executing...
	@bin\bluebird.exe
