binary:
	@echo running compiler...
	@csc src\main.cs src\pingStuff.cs src\helpCommand.cs src\emergency.cs src\debug.cs -out:bin\bluebird.exe -nologo
clean:
	@echo deleting binary...
	@del bin\bluebird.exe
run:
	@echo executing...
	@bin\bluebird.exe
